### ISSUE TITLE
getting error while executing segment_signal fucntion

### ISSUE THREAD

**Issue by kinjal129** [bharatm11/1D_CNN_Human_activity_recognition#2]
i m getting error while executing these lines of code-
segments, labels = segment_signal(dataset,window_size=90)
labels = np.asarray(pd.get_dummies(labels), dtype = np.int64)
reshaped_segments = segments.reshape(len(segments), 1,90, 3)

 and unable to resolve it .Please help me out.Thanks in advance.
ERROR-
RuntimeWarning: The input array could not be properly checked for nan values. nan values will be ignored.
  "values. nan values will be ignored.", RuntimeWarning)

**Comment by bharatm11** [comment]
Hi @kinjal129,

That is only a warning and doesn't affect the functioning of the code. It should work fine. Thank you for your interest in my repo.

Best,
@bharatm11
